### ISSUE TITLE
Tags not showing in packagist

### ISSUE THREAD

**Issue by tombroucke** [twikey/woocommerce-3.x#2]
Hi,

Thanks for publishing the package to packagist, but packagist is missing the tags. Only dev-master is available, and is not stable.
Can you add the tags (mainly 2.3)?

Thanks,
Tom

**Comment by koen-serry** [comment]
Thank you for noticing it. Probably packagist only registers the tags upon push. I've added a new tag 2.3.1 (separate from 2.3 as you pull request is also in there).
